# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
