# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_auto_20191121_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='amount_rewarded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
