# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_auto_20191121_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='amount_rewarded',
            new_name='amount_awarded',
        ),
    ]
