# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_auto_20191121_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
